markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: honinbou
host: iguowei.net

custom:
    category:
        thinking: 闭门思考
        problems: 问题记录
        knowledge: 知识经验
    categories:
      - name:  thinking
        title: 闭门思考

      - name:  problems
        title: 问题记录

      - name:  knowledge
        title: 知识经验

meta:
    author:
        name: honinbou
        email: weiguo85@gmail.com
        #disqus: your-disqus-short-name              # Disqus缩略标识
        #gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        #github: your-github-account                 # GitHub账号
        #gravatar: 1cd8c12591616d8c22aaa624f8c07834  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
